name: Deploy to itch.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm Kur
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Bağımlılıkları Yükle
        run: pnpm install --ignore-scripts

      - name: Build Al
        run: pnpm build

      - name: Butler Kur
        uses: remarkablegames/setup-butler@v3

      - name: itch.io'ya Yükle
        run: butler push dist oraz-chollaev/invictus-tournament-maker:html5
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
